# Generated by Django 2.2.10 on 2022-06-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='手机号')),
                ('u_name', models.CharField(max_length=64, verbose_name='姓名')),
                ('u_email', models.CharField(max_length=64, verbose_name='邮箱')),
                ('u_password', models.CharField(max_length=256, verbose_name='密码')),
                ('is_delete', models.BooleanField(default=False, verbose_name='账号是否已删除')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'user_table',
            },
        ),
    ]
